### ISSUE TITLE
Any chance you can attach an OSS license to this?

### ISSUE THREAD

**Issue by glennblock** [jorendorff/toy-calculator#1]
I'd like to use the parser and part of the backend.

**Comment by jorendorff** [comment]
Thanks for the nudge! Fixed in rev 866b6c6.

**Comment by glennblock** [comment]
Sweet. I have a PR to send for exponents and decimals!

✊

**Comment by glennblock** [comment]
Thanks!

**Comment by jorendorff** [comment]
> Sweet. I have a PR to send for exponents and decimals!

Sounds great! What are you using this for?

The intended use is learning—so it would be really cool to have these commits in the repo, not in `master`, but in a branch that people can check out after reading the minimal version.
